# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ad3eea8cbb595af3cd4cb677d0135a59003395f13c4ce4619b3781a06242b7cab1b958df9a81b532349118c82087e87ee99508da1e2c8118fef4532ef724c55

test:
  secret_key_base: a35463087815748ce797a3dd3fe03fd8b2504cc449eb522b65c741a360f8770b0254c06cf0a85f84aa624d48e40c72980efdd5aefc4bce727ee7975c9eedd50c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
